"use client";
import { useState } from "react";

type Category="Cuscuz"|"Tapioca"|"Bebidas";
type Product={id:string;name:string;category:Category;price:number;description:string;image:string;customizable?:boolean};
type Extra={id:string;name:string;price:number};
type CartItem={key:string;product:Product;extras:Extra[];quantity:number};
const products:Product[]=[
 {id:"amostrado",name:"Cuscuz Amostrado",category:"Cuscuz",price:15,description:"Uma combinação bem servida, com sabores da casa.",image:"/cuscuz-amostrado.jpg",customizable:true},
 {id:"nordestino",name:"Nordestino Cremoso",category:"Cuscuz",price:14,description:"Cuscuz macio e cremoso, preparado na hora.",image:"/cuscuz-hero.jpg",customizable:true},
 {id:"carne-sol",name:"Carne de Sol",category:"Cuscuz",price:13,description:"Cuscuz quentinho com carne de sol desfiada.",image:"/cuscuz-carne-sol.jpg",customizable:true},
 {id:"carne-moida-ovo",name:"Carne Moída com Ovo",category:"Cuscuz",price:12,description:"Carne moída temperada e ovo sobre cuscuz.",image:"/cuscuz-amostrado.jpg",customizable:true},
 {id:"calabresa",name:"Calabresa",category:"Cuscuz",price:10,description:"Calabresa dourada com cuscuz bem quentinho.",image:"/cuscuz-hero.jpg",customizable:true},
 {id:"frango",name:"Frango com Catupiry",category:"Cuscuz",price:10,description:"Frango temperado com recheio cremoso.",image:"/cuscuz-carne-sol.jpg",customizable:true},
 {id:"queijo",name:"Queijo",category:"Cuscuz",price:9,description:"Cuscuz simples com queijo bem derretido.",image:"/cuscuz-amostrado.jpg",customizable:true},
 {id:"tap-carne-sol",name:"Carne de Sol",category:"Tapioca",price:13,description:"Tapioca leve com recheio de carne de sol.",image:"/tapioca.jpg",customizable:true},
 {id:"tap-frango",name:"Frango com Catupiry",category:"Tapioca",price:10,description:"Frango temperado com recheio cremoso.",image:"/tapioca.jpg",customizable:true},
 {id:"tap-queijo",name:"Queijo",category:"Tapioca",price:9,description:"Queijo derretido em uma tapioca fresquinha.",image:"/tapioca.jpg",customizable:true},
 {id:"tap-carne-moida",name:"Carne Moída",category:"Tapioca",price:10,description:"Carne moída bem temperada e recheio generoso.",image:"/tapioca.jpg",customizable:true},
 {id:"tap-calabresa",name:"Calabresa com Queijo",category:"Tapioca",price:10,description:"Calabresa dourada com queijo derretido.",image:"/tapioca.jpg",customizable:true},
 {id:"tap-nutella",name:"Nutella com Morango",category:"Tapioca",price:12,description:"Combinação doce de creme de avelã e morango.",image:"/tapioca.jpg"},
 {id:"coca-250",name:"Coca-Cola Zero 250 ml",category:"Bebidas",price:3,description:"Gelada para acompanhar seu pedido.",image:"/bebida.svg"},
 {id:"guarana-250",name:"Guaraná 250 ml",category:"Bebidas",price:3,description:"Gelado para acompanhar seu pedido.",image:"/bebida.svg"},
 {id:"coca-lata",name:"Coca-Cola Zero lata",category:"Bebidas",price:5,description:"Lata gelada para acompanhar seu pedido.",image:"/bebida.svg"},
 {id:"sucos",name:"Sucos",category:"Bebidas",price:6,description:"Consulte os sabores disponíveis no WhatsApp.",image:"/suco.svg"}
];
const extras:Extra[]=[{id:"queijo-extra",name:"Queijo",price:3},{id:"ovo-extra",name:"Ovo",price:2},{id:"manteiga-extra",name:"Manteiga extra",price:1.5}];
const categories:Category[]=["Cuscuz","Tapioca","Bebidas"];
const money=(v:number)=>v.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});

export function MenuApp(){
 const [category,setCategory]=useState<Category>("Cuscuz"),[selected,setSelected]=useState<Product|null>(null),[selectedExtras,setSelectedExtras]=useState<string[]>([]),[productQty,setProductQty]=useState(1),[cart,setCart]=useState<CartItem[]>([]),[cartOpen,setCartOpen]=useState(false),[orderType,setOrderType]=useState<"Entrega"|"Retirada">("Entrega"),[name,setName]=useState(""),[address,setAddress]=useState(""),[payment,setPayment]=useState(""),[notes,setNotes]=useState("");
 const visible=products.filter(p=>p.category===category),itemCount=cart.reduce((s,i)=>s+i.quantity,0),subtotal=cart.reduce((s,i)=>s+(i.product.price+i.extras.reduce((x,e)=>x+e.price,0))*i.quantity,0),currentExtras=extras.filter(e=>selectedExtras.includes(e.id)),currentTotal=selected?(selected.price+currentExtras.reduce((s,e)=>s+e.price,0))*productQty:0;
 const choose=(p:Product)=>{setSelected(p);setSelectedExtras([]);setProductQty(1)};
 const addSelected=()=>{if(!selected)return;const chosen=selected.customizable?currentExtras:[],key=`${selected.id}-${chosen.map(e=>e.id).sort().join("-")}`;setCart(old=>{const found=old.find(i=>i.key===key);return found?old.map(i=>i.key===key?{...i,quantity:i.quantity+productQty}:i):[...old,{key,product:selected,extras:chosen,quantity:productQty}]});setSelected(null)};
 const changeQty=(key:string,d:number)=>setCart(old=>old.map(i=>i.key===key?{...i,quantity:i.quantity+d}:i).filter(i=>i.quantity>0));
 const sendWhatsApp=()=>{const lines=["Olá! Quero fazer este pedido:",""];cart.forEach(i=>{const unit=i.product.price+i.extras.reduce((s,e)=>s+e.price,0);lines.push(`${i.quantity}x ${i.product.name} — ${money(unit*i.quantity)}`);if(i.extras.length)lines.push(`Adicionais: ${i.extras.map(e=>`${e.name} (+${money(e.price)})`).join(", ")}`);lines.push("")});lines.push(`Subtotal: ${money(subtotal)}`,`Tipo do pedido: ${orderType}`);if(orderType==="Entrega")lines.push("Taxa de entrega: a confirmar");lines.push(`Total parcial: ${money(subtotal)}`,"",`Nome: ${name||"a informar"}`);if(orderType==="Entrega")lines.push(`Endereço: ${address||"a informar"}`);lines.push(`Forma de pagamento: ${payment||"a informar"}`);if(notes)lines.push(`Observações: ${notes}`);window.open(`https://wa.me/558897309179?text=${encodeURIComponent(lines.join("\n"))}`,"_blank","noopener,noreferrer")};
 return <main>
  <header className="hero"><nav className="topbar" aria-label="Navegação principal"><a className="brand" href="#inicio" aria-label="Marmitinha Delivery — início"><span className="brand-mark">M</span><span><strong>Marmitinha</strong><small>Delivery</small></span></a><span className="open-pill"><i/> Pedidos pelo WhatsApp</span></nav><div className="hero-copy" id="inicio"><p className="eyebrow">Feito na hora, do jeitinho nordestino</p><h1>Seu cuscuz favorito,<br/><em>pronto para pedir.</em></h1><p>Escolha seu prato, acrescente os adicionais e envie o pedido direto para a gente.</p><a className="hero-cta" href="#cardapio">Ver cardápio <span>↓</span></a></div></header>
  <section className="menu-shell" id="cardapio"><div className="section-heading"><div><p className="eyebrow">Escolha sem pressa</p><h2>Nosso cardápio</h2></div><p>Toque em um item para escolher adicionais.</p></div><div className="category-tabs" aria-label="Categorias">{categories.map(c=><button className={category===c?"active":""} key={c} onClick={()=>setCategory(c)} aria-pressed={category===c}>{c}<span>{products.filter(p=>p.category===c).length}</span></button>)}</div><div className="menu-grid" aria-live="polite">{visible.map(i=><article className="product-card" key={i.id} onClick={()=>choose(i)}><img src={i.image} alt={i.category==="Bebidas"?i.name:`${i.name} da Marmitinha`}/><div className="product-info"><p className="product-kind">{i.category}</p><h3>{i.name}</h3><p>{i.description}</p><div><strong>{money(i.price)}</strong><button type="button" onClick={e=>{e.stopPropagation();choose(i)}} aria-label={`${i.customizable?"Escolher":"Adicionar"} ${i.name}`}>{i.customizable?"Escolher":"Adicionar"}<span>+</span></button></div></div></article>)}</div></section>
  <button className="cart-dock" onClick={()=>setCartOpen(true)} aria-label={`Abrir pedido com ${itemCount} itens`}><div><span>Seu pedido</span><strong>{itemCount?`${itemCount} ${itemCount===1?"item":"itens"} · ${money(subtotal)}`:"Comece escolhendo um item"}</strong></div><b>Ver pedido <span>{itemCount}</span></b></button>
  {selected&&<div className="overlay" role="presentation" onMouseDown={()=>setSelected(null)}><section className="sheet product-sheet" role="dialog" aria-modal="true" aria-labelledby="product-title" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)} aria-label="Fechar">×</button><img className="sheet-photo" src={selected.image} alt=""/><div className="sheet-body"><p className="eyebrow">{selected.category}</p><h2 id="product-title">{selected.name}</h2><p className="sheet-description">{selected.description}</p><strong className="sheet-price">A partir de {money(selected.price)}</strong>{selected.customizable&&<fieldset className="extras"><legend>Quer acrescentar algo? <small>Opcional</small></legend>{extras.map(e=><label key={e.id}><input type="checkbox" checked={selectedExtras.includes(e.id)} onChange={()=>setSelectedExtras(old=>old.includes(e.id)?old.filter(id=>id!==e.id):[...old,e.id])}/><span>{e.name}</span><strong>+ {money(e.price)}</strong></label>)}</fieldset>}<div className="quantity"><span>Quantidade do item</span><div><button onClick={()=>setProductQty(q=>Math.max(1,q-1))} aria-label="Diminuir quantidade">−</button><strong>{productQty}</strong><button onClick={()=>setProductQty(q=>q+1)} aria-label="Aumentar quantidade">+</button></div></div><button className="primary-action" onClick={addSelected}>Adicionar ao pedido <span>{money(currentTotal)}</span></button></div></section></div>}
  {cartOpen&&<div className="overlay" role="presentation" onMouseDown={()=>setCartOpen(false)}><aside className="sheet cart-sheet" role="dialog" aria-modal="true" aria-labelledby="cart-title" onMouseDown={e=>e.stopPropagation()}><div className="cart-head"><div><p className="eyebrow">Quase lá</p><h2 id="cart-title">Seu pedido</h2></div><button className="close static" onClick={()=>setCartOpen(false)} aria-label="Fechar pedido">×</button></div><div className="cart-scroll">{!cart.length?<div className="empty-cart"><span>◇</span><h3>Seu pedido está vazio</h3><p>Escolha um item do cardápio para começar.</p><button onClick={()=>setCartOpen(false)}>Voltar ao cardápio</button></div>:<><div className="cart-items">{cart.map(i=>{const unit=i.product.price+i.extras.reduce((s,e)=>s+e.price,0);return <article className="cart-item" key={i.key}><img src={i.product.image} alt=""/><div><h3>{i.product.name}</h3>{i.extras.length>0&&<p>{i.extras.map(e=>e.name).join(", ")}</p>}<strong>{money(unit*i.quantity)}</strong><div className="cart-qty"><button onClick={()=>changeQty(i.key,-1)} aria-label={`Diminuir ${i.product.name}`}>−</button><span>{i.quantity}</span><button onClick={()=>changeQty(i.key,1)} aria-label={`Aumentar ${i.product.name}`}>+</button><button className="remove" onClick={()=>setCart(old=>old.filter(x=>x.key!==i.key))}>Remover</button></div></div></article>})}</div><div className="order-form"><h3>Como você quer receber?</h3><div className="type-toggle"><label><input type="radio" checked={orderType==="Entrega"} onChange={()=>setOrderType("Entrega")}/> Entrega</label><label><input type="radio" checked={orderType==="Retirada"} onChange={()=>setOrderType("Retirada")}/> Retirada</label></div><label>Seu nome<input value={name} onChange={e=>setName(e.target.value)} placeholder="Como podemos chamar você?"/></label>{orderType==="Entrega"&&<label>Endereço<input value={address} onChange={e=>setAddress(e.target.value)} placeholder="Rua, número e bairro"/></label>}<label>Forma de pagamento<select value={payment} onChange={e=>setPayment(e.target.value)}><option value="">Escolha no WhatsApp</option><option>Pix</option><option>Dinheiro</option><option>Cartão</option></select></label><label>Observações<textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Ex.: sem cebola, troco para R$ 50..."/></label></div><div className="summary"><p><span>Subtotal</span><strong>{money(subtotal)}</strong></p><p><span>Entrega</span><strong>A confirmar</strong></p><p className="total"><span>Total parcial</span><strong>{money(subtotal)}</strong></p><small>O pedido será confirmado após nosso atendimento responder.</small></div></>}</div>{cart.length>0&&<div className="cart-footer"><button className="whatsapp" onClick={sendWhatsApp}><span>◉</span> Enviar pedido pelo WhatsApp</button></div>}</aside></div>}
 </main>
}
